### ISSUE TITLE
Python 2 Support

### ISSUE THREAD

**Issue by dmtucker** [dmtucker/keysmith#12]
```
$ docker run --rm -it python:latest bash
root@5241a7ac920b:/# pip install keysmith
Collecting keysmith
  Downloading keysmith-1.0.1.tar.gz (140kB)
    100% |████████████████████████████████| 143kB 349kB/s 
Installing collected packages: keysmith
  Running setup.py install for keysmith ... done
Successfully installed keysmith-1.0.1
```

```
$ docker run --rm -it python:2 bash
root@813e7bb9b2e2:/# pip install keysmith
Collecting keysmith
  Downloading keysmith-1.0.1.tar.gz (140kB)
    100% |████████████████████████████████| 143kB 509kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-KFoubo/keysmith/setup.py", line 12, in <module>
        import keysmith
      File "/tmp/pip-build-KFoubo/keysmith/keysmith/__init__.py", line 3, in <module>
        from keysmith.keysmith import Key
    ImportError: No module named keysmith

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-KFoubo/keysmith/
```

This occurs because `__init__.py` is missing the following statement:

``` python
from __future__ import absolute_import
```

There is another problem though: why didn't Travis catch this?

**Comment by dmtucker** [comment]
Oh ya... this package doesn't support Python 2 (should it?): https://github.com/dmtucker/keysmith/blob/master/setup.py#L34

This should work in most environments:

``` sh
pip3 install keysmith
```

**Comment by dmtucker** [comment]
If this is an issue, use [xkcdpass](https://github.com/redacted/XKCD-password-generator).
